name: 'Run tests'
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        version: [2023-09, 2023-10, 2023-11, 2023-12, latest]
    runs-on: ubuntu-latest
    container:
      image: docker.io/firedrakeproject/firedrake-vanilla:${{ matrix.version }}
      options: --user root
    steps:
      - name: Activate Firedrake virtual environment
        run: |
          . /home/firedrake/firedrake/bin/activate
          echo PATH=$PATH >> $GITHUB_ENV
      - name: Install dependencies
        run: |
          apt update
          apt install -yq patchelf
          pip install netCDF4 matplotlib
          pip install git+https://github.com/icepack/Trilinos.git
          pip install git+https://github.com/icepack/pyrol.git
          pip install git+https://github.com/icepack/icepack.git
      - name: Check out git repository
        uses: actions/checkout@v3
      - name: Run tests
        env:
          EARTHDATA_USERNAME: ${{ secrets.EARTHDATA_USERNAME }}
          EARTHDATA_PASSWORD: ${{ secrets.EARTHDATA_PASSWORD }}
        run: |
          python initialize.py
          python make_plot.py
      - name: Upload result
        uses: actions/upload-artifact@v3
        with:
          name: kangerdlugssuaq
          path: kangerdlugssuaq.png
